#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.zzk.entity
  mapperLocations: classpath:mapper/*.xml

---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://120.55.49.68:3306/zsxx_line?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zsxx123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource


logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug
    
#分页插件    
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql
